import { useEffect, useState } from "react";
import type { TelemetryOutboxStatus } from "@_89/super-brain-client";
import type { FoldApiClient } from "../api";
import type { ProcessingStatus as Processing } from "../types";
import { BrowserTelemetryOutbox } from "../telemetry-outbox";
import { formatDateTime } from "../format";

export function ProcessingStatus({ processing, api, outbox }: { readonly processing?: Processing; readonly api: FoldApiClient; readonly outbox?: BrowserTelemetryOutbox }) {
  const [telemetry, setTelemetry] = useState<TelemetryOutboxStatus>(); const [repairError, setRepairError] = useState<string>(); const [pending, setPending] = useState(false);
  useEffect(() => { let active = true; const refresh = () => { void api.telemetryStatus().then((status) => { if (active) setTelemetry(status); }); }; refresh(); const timer = window.setInterval(refresh, 10_000); return () => { active = false; window.clearInterval(timer); }; }, [api]);
  const repair = async (action: "retry" | "clear") => { if (outbox === undefined) return; setPending(true); setRepairError(undefined); try { await api.canonical.repairTelemetry(action === "retry" ? "retry" : "discard-terminal"); if (action === "retry") await outbox.flush(); setTelemetry(await api.telemetryStatus()); } catch (caught) { setRepairError(caught instanceof Error ? caught.message : "Feedback delivery is unavailable"); } finally { setPending(false); } };
  const fresh = processing?.available && Date.now() - Date.parse(processing.observedAt) <= 60_000;
  return <section className="panel panel--processing" aria-label="Processing and feedback delivery"><header className="panel__header"><div><span className="eyebrow">Evidence pipeline</span><h2>Local worker processing</h2></div><span>{processing?.observedAt === undefined ? "No worker report" : `Observed ${formatDateTime(Date.parse(processing.observedAt))}`}</span></header>
    {fresh && processing.available ? <><dl className="processing-counts">{(["pending", "waiting", "retry", "completed", "excluded", "exhausted"] as const).map((state) => <div key={state}><dt>{state}</dt><dd>{processing.coverage[state]}</dd></div>)}</dl><p className="evidence-note">{processing.lagMs === undefined ? "Processing lag is unmeasured." : `Oldest pending work: ${Math.round(processing.lagMs / 1000)} seconds.`} Completion means a processing job ended; excluded work is not usable evidence.</p></> : <p className="evidence-note">Worker status unavailable{processing?.available === false ? ` (${processing.reason.replaceAll("-", " ")})` : processing === undefined ? ". Connect local operator access to inspect it." : " (report is stale)."}</p>}
    <section className="delivery-status"><h3>Feedback delivery</h3>{telemetry === undefined ? <p>Loading delivery status</p> : <><p>{telemetry.pending} pending · {telemetry.retry} retrying · {telemetry.denied} denied · {telemetry.exhausted} need attention</p>{telemetry.unavailable !== undefined && <p className="field-error" role="status">{telemetry.unavailable}</p>}<p className="evidence-note">Optional delivery failure does not block recall. Only identifiers and reported signals are stored locally; another account's queue stays separate.</p>{outbox !== undefined && (telemetry.denied + telemetry.exhausted > 0 || telemetry.unavailable !== undefined) && <div className="detail-pane__actions"><button type="button" className="button button--secondary" disabled={pending} onClick={() => void repair("retry")}>Retry failed delivery</button><button type="button" className="text-button" disabled={pending} onClick={() => void repair("clear")}>Clear failed signals</button></div>}</>}{repairError !== undefined && <p className="field-error" role="alert">{repairError}</p>}</section>
  </section>;
}
